name: Steve_repo
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - matplotlib
  - scipy
  - numpy
  - jupyter
  - nbformat
  - pip
  - pip:
    - vtk
    - pyqt5
    - mayavi

    
