name: Steve_repo
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - matplotlib
  - vtk
  - scipy
  - numpy
  - jupyter
  - nbformat
  - mayavi
  - pip
  - pip:
    - nmrglue
    - pyqt5
